import {
    GET_DAIRYS,
    FILTER_BY,
    OPEN,
    CLOSE,
    FILTER_BY_USER,
    FILTER_BY_NAME,
    GET_DATA,
} from "./actionTypes";

export const getDairys = () => {
    return {
        type: GET_DAIRYS,
        payload: dairyJson,
    };
};

const mapPathsToProps = {
    "/dairys": "",
    "/dairys/new": "Новый",
    "/dairys/pinned": "Прикреплен",
    "/dairys/conflicts": "Конфликт",
};

export const filterByStatus = (payload) => {
    const prop = mapPathsToProps[payload];
    const dairys = prop === "" ? dairyJson : dairyJson.filter((item) => item.status === prop);
    return {
        type: FILTER_BY,
        dairys,
    };
};

export const filterByUser = (payload) => {
    const dairys =
        payload === "" ? dairyJson : dairyJson.filter((item) => item.user.includes(payload));

    return {
        type: FILTER_BY_USER,
        payload: dairys,
    };
};

export const getRabotyagi = () => {
    return {
        type: GET_DATA,
        payload: rabotyagi,
    };
};

export const filterByName = (payload) => {
    const filter =
        payload === "" ? rabotyagi : rabotyagi.filter((item) => item.name.includes(payload));
    return {
        type: FILTER_BY_NAME,
        payload: filter,
    };
};

export const open = () => {
    return { type: OPEN, rabotyagi: rabotyagi, dairyJson: dairyJson };
};
export const close = () => {
    return { type: CLOSE, rabotyagi: rabotyagi, dairyJson: dairyJson };
};

const rabotyagi = [
    {
        name: "Keri Dunlap",
        rating: 10,
        clients: 2,
        dairys: 9,
        nagruzka: 2,
        tags: ["consectetur", "non", "reprehenderit"],
        commet:
            "Ea quis aliquip deserunt mollit voluptate reprehenderit est non esse aliqua irure cupidatat dolore occaecat. Cillum anim proident est cupidatat anim non cillum non irure esse sunt nulla adipisicing. Id anim adipisicing esse magna sit.",
    },
    {
        name: "April Hill",
        rating: 48,
        clients: 2,
        dairys: 7,
        nagruzka: 10,
        tags: ["nisi", "do", "et"],
        commet:
            "Nulla officia aliquip qui ea id deserunt non ipsum. Consequat reprehenderit dolore mollit culpa mollit exercitation est do velit ex ut. Cillum laboris ut aute sit quis eiusmod non. Nostrud id id enim in consequat pariatur ipsum occaecat officia non cupidatat quis consequat nisi. Sit et consequat laborum eiusmod in sunt. Lorem eiusmod aliquip veniam consectetur Lorem dolore cupidatat mollit cillum est qui Lorem. Amet commodo culpa pariatur nostrud occaecat fugiat officia eu consectetur nulla minim amet sint.",
    },
    {
        name: "Craig Baxter",
        rating: 98,
        clients: 2,
        dairys: 3,
        nagruzka: 9,
        tags: ["commodo"],
        commet:
            "Aliquip consequat adipisicing laboris officia est pariatur sit laboris. Eiusmod occaecat id minim eu et id dolore elit. Incididunt ipsum proident Lorem culpa dolore labore officia. Sit aute sit duis sint reprehenderit consectetur non sunt laboris. Cupidatat nostrud tempor incididunt deserunt aute ea irure fugiat dolor tempor nulla eu Lorem.",
    },
    {
        name: "Prince Church",
        rating: 86,
        clients: 6,
        dairys: 3,
        nagruzka: 2,
        tags: ["ipsum", "ea", "ex"],
        commet:
            "Voluptate est aute id sit pariatur ad aliquip. Minim pariatur sint reprehenderit deserunt. Ipsum nulla adipisicing nostrud irure Lorem veniam ut proident quis Lorem adipisicing minim. Elit Lorem in proident non.",
    },
    {
        name: "Huffman Garcia",
        rating: 42,
        clients: 4,
        dairys: 1,
        nagruzka: 5,
        tags: ["ex", "mollit"],
        commet:
            "Sunt est tempor elit proident consectetur adipisicing dolor velit excepteur culpa minim quis. Deserunt qui do deserunt pariatur nisi reprehenderit in culpa nisi. Minim adipisicing exercitation sunt cupidatat et tempor. Commodo laborum nulla voluptate aliquip amet irure.",
    },
    {
        name: "Sykes Ramirez",
        rating: 37,
        clients: 6,
        dairys: 1,
        nagruzka: 9,
        tags: ["est", "ipsum", "adipisicing"],
        commet:
            "Ad id incididunt et duis pariatur anim deserunt ea nostrud exercitation. Sint pariatur adipisicing ea aute ut irure velit occaecat veniam pariatur proident laborum magna nostrud. Quis magna commodo excepteur eu est. Sunt quis eu tempor consectetur occaecat fugiat. Consequat duis cupidatat ad sunt aliquip et aliquip ex do. Cillum sunt sunt anim commodo voluptate quis aliquip esse nisi elit. Do laborum est cupidatat pariatur.",
    },
    {
        name: "Ingrid Curry",
        rating: 22,
        clients: 6,
        dairys: 1,
        nagruzka: 1,
        tags: ["et", "ea", "laborum"],
        commet:
            "Aute commodo eu labore Lorem incididunt consectetur velit. Consequat mollit commodo in occaecat. Sint dolor sunt ut eu laboris minim do fugiat non aute et. Est pariatur sit fugiat exercitation amet proident deserunt dolore qui. Cillum quis do ea veniam tempor commodo voluptate eu tempor proident ea commodo.",
    },
    {
        name: "Theresa Holloway",
        rating: 68,
        clients: 1,
        dairys: 2,
        nagruzka: 1,
        tags: ["pariatur"],
        commet:
            "Eu aute aliquip ullamco tempor officia incididunt ut pariatur fugiat. Officia et sunt reprehenderit duis dolor. Cillum consequat sit enim aute ut dolor tempor qui aute consectetur. Aliquip veniam irure pariatur laboris sint do voluptate ea fugiat veniam commodo qui dolor duis. Sunt irure nulla ipsum ipsum voluptate ad.",
    },
    {
        name: "Brock Alvarado",
        rating: 57,
        clients: 1,
        dairys: 8,
        nagruzka: 10,
        tags: ["veniam", "in", "nisi"],
        commet:
            "Proident consequat eiusmod labore occaecat Lorem commodo. Deserunt incididunt aliqua laboris nostrud aute velit ullamco. Aute labore quis amet duis qui laboris. Quis laboris qui officia sint enim minim commodo adipisicing reprehenderit incididunt. In cillum velit cupidatat officia anim enim ut duis ex. Id sit ea enim eu eiusmod duis consectetur ut nulla aliquip.",
    },
    {
        name: "Mcdowell Dickerson",
        rating: 83,
        clients: 6,
        dairys: 8,
        nagruzka: 8,
        tags: ["est", "deserunt", "est", "nostrud", "pariatur"],
        commet:
            "Ullamco quis voluptate voluptate aliquip ullamco aliquip et sint deserunt ut ullamco qui et. Magna nostrud sunt aliquip duis culpa aliqua quis ad aliqua nisi pariatur enim irure amet. Exercitation aliqua consectetur nisi incididunt ad do aute. Cillum amet est excepteur id dolore cupidatat irure et enim elit quis id excepteur. Cillum sint excepteur irure ut officia. Officia aute ullamco voluptate enim.",
    },
    {
        name: "Pruitt Garner",
        rating: 36,
        clients: 5,
        dairys: 1,
        nagruzka: 9,
        tags: ["laboris", "cillum", "laborum"],
        commet:
            "Sunt voluptate aute voluptate nisi. Et laboris et mollit esse. Aliqua commodo ad minim nostrud excepteur et est deserunt. Proident voluptate in esse esse ipsum consequat duis commodo nisi.",
    },
    {
        name: "Hancock Burt",
        rating: 85,
        clients: 6,
        dairys: 4,
        nagruzka: 2,
        tags: ["incididunt", "fugiat", "ullamco", "aute"],
        commet:
            "Aliqua ipsum ad officia enim exercitation sit quis veniam laboris culpa dolore anim. Ex qui tempor tempor fugiat velit ea id et fugiat officia nulla. Consectetur tempor consectetur nulla excepteur tempor cillum enim labore do officia nostrud ea eu eu. Dolor Lorem id et eu Lorem ad minim fugiat deserunt. Fugiat laborum qui ex laboris sit consectetur cillum. Dolor voluptate aliquip consectetur fugiat anim ad sint ad et eiusmod id.",
    },
    {
        name: "Clay Jenkins",
        rating: 79,
        clients: 9,
        dairys: 3,
        nagruzka: 3,
        tags: ["sunt", "sunt"],
        commet:
            "Dolore sint ullamco aliqua exercitation aute nulla enim amet occaecat veniam commodo sint non. Irure duis minim in ex occaecat enim sit consequat mollit aliquip nostrud tempor consectetur. Velit ex laborum non aliqua ea ex elit consequat esse in officia exercitation aute est. Duis est cillum irure mollit et in sunt mollit fugiat velit. Ad ex enim veniam occaecat eu cupidatat minim irure minim qui ullamco laborum non. Magna aliqua exercitation et qui officia minim. Deserunt duis excepteur amet dolor nisi esse ea labore laborum cupidatat dolore.",
    },
    {
        name: "Walker Swanson",
        rating: 67,
        clients: 8,
        dairys: 3,
        nagruzka: 8,
        tags: ["esse", "nisi"],
        commet:
            "Mollit cillum voluptate sunt laboris exercitation cillum est aute. Ex do dolor qui veniam velit voluptate amet. Et ad esse proident incididunt id. Deserunt ex veniam dolore consectetur laborum officia non officia ullamco consectetur dolor ex. Aliqua consequat laboris quis deserunt cillum labore esse cupidatat ipsum tempor est laboris. Irure Lorem nisi mollit cillum est culpa dolor labore voluptate consectetur labore id commodo.",
    },
    {
        name: "Elliott Nicholson",
        rating: 51,
        clients: 10,
        dairys: 5,
        nagruzka: 10,
        tags: ["sunt", "minim", "aliqua", "amet"],
        commet:
            "Aliquip sit ex incididunt quis amet ipsum enim Lorem consectetur id. Officia ea culpa dolore est dolor exercitation esse proident dolore esse est cillum excepteur. Commodo ipsum duis aliquip deserunt culpa est exercitation ipsum ex fugiat amet. Laborum et magna esse consequat adipisicing non duis. Tempor deserunt ipsum magna proident dolor occaecat. Nostrud ad officia sint consectetur laboris et Lorem qui et adipisicing minim. Excepteur ut veniam qui enim incididunt ad dolore pariatur id.",
    },
    {
        name: "Winnie Skinner",
        rating: 2,
        clients: 3,
        dairys: 1,
        nagruzka: 8,
        tags: ["sint"],
        commet:
            "Ea consequat duis nulla labore sint. Ex ad nulla labore voluptate dolore pariatur. Tempor aute nulla ut dolor est pariatur amet minim dolore Lorem consequat. Laborum ex tempor ad anim est.",
    },
    {
        name: "Tanisha Santiago",
        rating: 80,
        clients: 2,
        dairys: 2,
        nagruzka: 2,
        tags: ["nostrud"],
        commet:
            "Veniam aute pariatur duis reprehenderit. Nulla dolore pariatur proident officia eu quis consectetur fugiat eu qui. Ut ea laboris id veniam. Fugiat aliquip deserunt eu enim non consequat nulla quis ut id. Esse ut ea aliquip duis non.",
    },
    {
        name: "Rachelle Bowers",
        rating: 95,
        clients: 9,
        dairys: 2,
        nagruzka: 10,
        tags: ["consequat", "pariatur"],
        commet:
            "Nostrud amet mollit sint ad anim excepteur eiusmod amet anim occaecat. Sit consectetur sit elit velit laborum adipisicing ipsum laborum voluptate tempor officia aliquip pariatur consequat. Duis consequat culpa id laboris ullamco. Occaecat ut cillum do ipsum laborum eiusmod ex enim consectetur. Est cillum amet aliquip quis dolor magna reprehenderit aliquip dolore cupidatat.",
    },
    {
        name: "Maritza Meyers",
        rating: 56,
        clients: 4,
        dairys: 3,
        nagruzka: 10,
        tags: ["non", "voluptate"],
        commet:
            "Fugiat pariatur eu et nulla proident laboris ut veniam proident Lorem. Commodo aliquip adipisicing magna Lorem ea consectetur Lorem ullamco. Irure Lorem do elit laboris eiusmod ex enim do laborum.",
    },
    {
        name: "Dotson Vinson",
        rating: 46,
        clients: 6,
        dairys: 2,
        nagruzka: 8,
        tags: ["aute", "Lorem", "veniam"],
        commet:
            "Sunt et cupidatat ex deserunt excepteur ut commodo ullamco adipisicing pariatur ea. Irure minim ut occaecat qui sit elit et officia nulla. Consectetur in consequat eu deserunt fugiat magna officia irure ex dolor cillum consequat nostrud laboris. Lorem ex pariatur magna occaecat laboris. Esse excepteur officia nulla tempor pariatur laboris consectetur labore dolor quis cupidatat est eu. Exercitation ut quis adipisicing qui cupidatat qui veniam minim enim aute.",
    },
    {
        name: "Grace Hyde",
        rating: 83,
        clients: 9,
        dairys: 2,
        nagruzka: 10,
        tags: ["sint", "non", "aliquip"],
        commet:
            "Cupidatat laborum dolor officia tempor in Lorem. Laborum est duis veniam cupidatat deserunt minim quis non eiusmod sint irure dolor proident. Cillum laboris enim in dolore proident Lorem proident velit Lorem commodo.",
    },
    {
        name: "Kelsey Gomez",
        rating: 8,
        clients: 5,
        dairys: 8,
        nagruzka: 10,
        tags: ["consequat", "veniam", "et", "occaecat"],
        commet:
            "Proident elit culpa aliquip velit consectetur ea mollit nostrud consectetur est mollit. Nisi officia aliqua deserunt cillum consequat ex et culpa sit aliqua enim esse amet reprehenderit. Quis deserunt proident labore nostrud eiusmod dolor culpa ut amet est nostrud nulla consectetur nulla. Pariatur qui proident enim sunt anim laboris. Quis adipisicing ex Lorem non incididunt elit eiusmod ad ullamco in aute ipsum voluptate adipisicing.",
    },
    {
        name: "Ester Hardy",
        rating: 71,
        clients: 8,
        dairys: 2,
        nagruzka: 6,
        tags: ["deserunt", "non", "quis", "est"],
        commet:
            "Occaecat aliqua dolor proident in ipsum sit do sint excepteur magna duis exercitation laborum. Reprehenderit aliquip id ea aliqua qui minim nisi tempor id occaecat. Ullamco ea irure amet ea consectetur sint velit deserunt dolore labore eiusmod. Sunt fugiat cillum deserunt cillum sunt ut sint duis. Incididunt excepteur aute esse deserunt. Exercitation reprehenderit incididunt dolore magna proident cupidatat ut sunt reprehenderit dolore incididunt. Fugiat Lorem pariatur eu consectetur ea Lorem culpa.",
    },
    {
        name: "Macdonald Harrington",
        rating: 75,
        clients: 5,
        dairys: 3,
        nagruzka: 2,
        tags: ["duis", "magna", "aliquip", "tempor"],
        commet:
            "Ad ex sit anim ea ipsum quis deserunt magna in incididunt. Dolore anim ipsum nisi occaecat enim nostrud anim pariatur occaecat enim. Commodo officia duis in ex adipisicing. Velit sint ut mollit ullamco. Voluptate dolor eiusmod nulla consectetur consectetur ea.",
    },
    {
        name: "Lynch Gibson",
        rating: 88,
        clients: 4,
        dairys: 8,
        nagruzka: 8,
        tags: ["esse", "eiusmod"],
        commet:
            "Dolor excepteur sit proident sit ipsum magna est laboris consectetur consequat. Adipisicing do ex enim sit exercitation proident. Ullamco et minim commodo ullamco sunt velit laboris nulla in commodo. Nisi irure labore reprehenderit incididunt. Officia est velit voluptate aliquip sunt aliquip dolore culpa.",
    },
    {
        name: "Roy Joyner",
        rating: 74,
        clients: 10,
        dairys: 10,
        nagruzka: 9,
        tags: ["enim"],
        commet:
            "Duis laborum quis id eiusmod amet tempor ea consequat veniam dolor ullamco. Reprehenderit eiusmod culpa qui aute. Non cillum velit proident occaecat exercitation. Et ipsum labore eu aliquip cillum nisi et elit.",
    },
    {
        name: "Cynthia Golden",
        rating: 29,
        clients: 6,
        dairys: 4,
        nagruzka: 4,
        tags: ["reprehenderit", "ipsum", "labore", "qui", "nisi"],
        commet:
            "Velit labore ullamco eu elit commodo consequat aliqua sunt nulla. Elit velit elit sit velit veniam amet veniam ut ut id consectetur incididunt ex. Aliquip sint consectetur consequat consectetur. Ad amet voluptate eiusmod deserunt irure. Cillum esse duis do cillum laborum. Ut do aliquip culpa exercitation consequat nisi quis proident. Ad proident non aute anim.",
    },
    {
        name: "Dawson Price",
        rating: 74,
        clients: 5,
        dairys: 1,
        nagruzka: 3,
        tags: ["fugiat"],
        commet:
            "Sunt esse aliquip qui dolor do veniam. In ea commodo excepteur officia commodo ea aliqua irure mollit reprehenderit. Irure tempor labore incididunt minim ut minim enim mollit officia tempor ex. Ipsum eu incididunt labore cillum ea deserunt nostrud proident qui excepteur in eu.",
    },
    {
        name: "Olson Fulton",
        rating: 10,
        clients: 1,
        dairys: 8,
        nagruzka: 7,
        tags: ["anim", "eiusmod"],
        commet:
            "Eu est Lorem ea reprehenderit aute. Pariatur ea do elit sunt incididunt magna non proident laborum labore nisi nostrud commodo in. Labore sunt est cillum ullamco magna enim cillum excepteur culpa deserunt.",
    },
    {
        name: "Mcfadden Green",
        rating: 95,
        clients: 3,
        dairys: 9,
        nagruzka: 7,
        tags: ["amet", "commodo", "cillum", "dolore"],
        commet:
            "Labore quis sint minim fugiat quis sint irure nostrud excepteur. Nulla ipsum incididunt laborum sunt exercitation do esse nisi. Laborum sint nulla velit excepteur sint labore. Deserunt duis ut excepteur sunt elit officia quis sint anim. Quis officia enim quis ut ad nostrud nostrud qui velit.",
    },
    {
        name: "Bullock Craig",
        rating: 6,
        clients: 1,
        dairys: 7,
        nagruzka: 3,
        tags: ["ipsum", "veniam"],
        commet:
            "Nostrud velit elit quis eu culpa. Qui et irure dolore voluptate aute sunt ut eiusmod incididunt officia. Ullamco cupidatat reprehenderit fugiat veniam.",
    },
    {
        name: "Etta Cummings",
        rating: 16,
        clients: 10,
        dairys: 1,
        nagruzka: 10,
        tags: ["sunt", "consectetur"],
        commet:
            "Id consectetur sint id esse dolore consectetur est culpa nostrud eu quis aute quis cillum. Ipsum proident non do deserunt. Sunt sint nulla incididunt velit in ullamco ex quis exercitation eiusmod quis proident. Reprehenderit velit ullamco veniam dolor. Excepteur do eiusmod sint anim incididunt esse minim qui cupidatat.",
    },
    {
        name: "Sharpe Hensley",
        rating: 70,
        clients: 9,
        dairys: 2,
        nagruzka: 9,
        tags: ["ipsum", "ad", "dolor", "anim", "cupidatat"],
        commet:
            "Ex eu voluptate fugiat eiusmod labore sunt voluptate in fugiat dolor. Voluptate adipisicing minim anim do enim aliqua ad tempor. Amet ad incididunt pariatur esse officia amet tempor cillum. Officia proident proident in labore enim pariatur labore deserunt quis nostrud. Do sit magna nisi pariatur culpa ullamco sit in aliquip voluptate id. Aliqua ut consectetur ut mollit nulla do. Qui non in enim nostrud exercitation minim.",
    },
    {
        name: "Cross Short",
        rating: 55,
        clients: 6,
        dairys: 5,
        nagruzka: 8,
        tags: ["eiusmod", "irure", "commodo", "elit", "adipisicing"],
        commet:
            "Exercitation et aliquip exercitation labore commodo duis dolor mollit fugiat minim ex. Tempor irure minim culpa ad reprehenderit do labore in qui do veniam ea. Dolor voluptate consequat Lorem eiusmod adipisicing enim duis ipsum reprehenderit culpa nisi nostrud ipsum duis.",
    },
    {
        name: "Lewis Mullen",
        rating: 93,
        clients: 6,
        dairys: 7,
        nagruzka: 1,
        tags: ["anim"],
        commet:
            "Eiusmod sunt ut magna amet veniam incididunt laborum labore commodo nulla pariatur. Do qui dolore dolor pariatur consectetur. Velit consequat deserunt pariatur magna. Sunt consectetur amet nulla aliquip proident enim in minim consequat anim et minim. Dolor ea cillum enim ut ipsum et est. Exercitation qui cupidatat mollit officia exercitation aliqua quis mollit eiusmod proident enim consequat sunt voluptate.",
    },
    {
        name: "Decker Gibbs",
        rating: 72,
        clients: 9,
        dairys: 10,
        nagruzka: 1,
        tags: ["dolore", "laboris"],
        commet:
            "Occaecat fugiat magna incididunt aliqua. Dolor et consequat esse incididunt aliquip adipisicing voluptate aute cupidatat voluptate nisi. Commodo Lorem reprehenderit qui dolor occaecat nulla mollit irure consectetur magna aliquip ut. Eu reprehenderit consequat eu cupidatat reprehenderit elit in cillum in aliqua nostrud fugiat est. Labore aute reprehenderit eiusmod nostrud culpa nisi veniam veniam aute dolore pariatur. Excepteur excepteur fugiat velit sint pariatur aliquip ea.",
    },
    {
        name: "Marianne Kennedy",
        rating: 73,
        clients: 6,
        dairys: 4,
        nagruzka: 10,
        tags: ["quis", "ad"],
        commet:
            "Enim irure excepteur velit esse dolore. Cillum Lorem dolor sit Lorem ea nulla esse esse. Qui velit incididunt et mollit anim dolore voluptate laborum in. Ut culpa aute ex irure et. Ut incididunt quis consectetur tempor consectetur velit esse anim veniam qui. Labore excepteur quis fugiat laboris qui ipsum est cupidatat.",
    },
    {
        name: "Calderon Ewing",
        rating: 44,
        clients: 5,
        dairys: 6,
        nagruzka: 5,
        tags: ["ea", "eiusmod", "consectetur", "Lorem", "dolore"],
        commet:
            "Laborum reprehenderit velit laborum nostrud dolore eiusmod est incididunt est nisi reprehenderit qui ullamco. Aute eu sunt ea incididunt qui anim consectetur commodo elit. Ipsum incididunt excepteur aute officia elit esse dolor.",
    },
    {
        name: "Elise Ramos",
        rating: 15,
        clients: 1,
        dairys: 3,
        nagruzka: 8,
        tags: ["duis", "magna", "sit"],
        commet:
            "Labore et veniam ad esse reprehenderit in fugiat culpa ut. Cillum anim laboris irure tempor ut magna. Mollit cupidatat cillum commodo exercitation. Pariatur est sint ex reprehenderit cupidatat occaecat exercitation ipsum consequat sint. Ipsum ullamco ad eiusmod sunt. Id ipsum ut consectetur sunt id nulla aute incididunt fugiat pariatur officia.",
    },
    {
        name: "Alvarez Chambers",
        rating: 73,
        clients: 7,
        dairys: 10,
        nagruzka: 8,
        tags: ["incididunt", "pariatur"],
        commet:
            "Commodo nisi consequat exercitation elit et pariatur. Ipsum est culpa ea laboris nulla duis duis sunt ea sit velit. Sit aliqua adipisicing nulla consequat anim cupidatat. Ea non ea laboris do officia voluptate qui.",
    },
    {
        name: "Jean Merrill",
        rating: 90,
        clients: 4,
        dairys: 6,
        nagruzka: 1,
        tags: ["sit", "reprehenderit", "voluptate", "non"],
        commet:
            "Ut consequat sunt sit aliqua aute ullamco. Minim quis anim sunt irure irure tempor veniam sunt nostrud nisi aliquip sunt amet. Dolor excepteur in sit labore consequat deserunt consequat adipisicing incididunt magna laboris est laborum eu. Lorem eiusmod ad aliqua ea dolore irure minim labore. Ipsum dolor tempor reprehenderit eu occaecat sit proident elit do in magna. Minim deserunt consequat anim aliqua elit Lorem sit pariatur sint aute ea et elit irure.",
    },
    {
        name: "Jami Gutierrez",
        rating: 50,
        clients: 7,
        dairys: 10,
        nagruzka: 7,
        tags: ["aliqua", "id"],
        commet:
            "Enim duis sunt culpa elit. Duis deserunt nulla sint sint laboris sunt est velit id occaecat irure eiusmod deserunt. Aliqua excepteur sit elit ut esse excepteur exercitation fugiat consectetur consectetur incididunt duis. Minim tempor ea sit eiusmod quis duis eiusmod deserunt magna sit eu.",
    },
    {
        name: "Kerry Parks",
        rating: 39,
        clients: 3,
        dairys: 5,
        nagruzka: 1,
        tags: ["irure", "est", "nisi"],
        commet:
            "Magna qui enim tempor nostrud. Voluptate dolor sint ad mollit eu deserunt eu reprehenderit enim sit sunt. Labore non fugiat dolor fugiat pariatur. Fugiat ut laboris est consectetur aute dolor. Sint dolor ipsum id fugiat.",
    },
    {
        name: "Sherrie Slater",
        rating: 62,
        clients: 2,
        dairys: 5,
        nagruzka: 10,
        tags: ["Lorem", "nulla", "laborum", "et"],
        commet:
            "Veniam et officia laborum reprehenderit. Aliquip ex ut dolor nulla id magna ipsum. Ipsum eiusmod quis et nulla ad labore labore anim ea esse dolore Lorem ex exercitation. Nostrud ipsum aliquip eiusmod aliquip non cillum tempor velit adipisicing veniam Lorem.",
    },
    {
        name: "Logan Rush",
        rating: 59,
        clients: 7,
        dairys: 5,
        nagruzka: 10,
        tags: ["exercitation", "duis", "cillum", "eiusmod"],
        commet:
            "Irure nisi qui reprehenderit elit tempor cillum minim nulla nostrud eu laboris Lorem. Excepteur do esse eiusmod ipsum sunt pariatur nisi dolor aliquip. Veniam et aliqua eiusmod consequat magna. Labore sunt voluptate sit elit sint magna do culpa excepteur consectetur commodo aliquip sit ad. Exercitation commodo aliquip dolore irure in pariatur.",
    },
    {
        name: "Jeanette Beach",
        rating: 52,
        clients: 4,
        dairys: 7,
        nagruzka: 6,
        tags: ["excepteur", "elit", "laborum", "ipsum", "ullamco"],
        commet:
            "Et voluptate laborum laboris mollit commodo labore velit ea officia do ex. Elit magna minim mollit pariatur aute incididunt ipsum. In minim et id aliquip laboris. Cillum voluptate occaecat voluptate consectetur aliqua proident labore nostrud. Deserunt enim laborum proident veniam irure anim occaecat eiusmod. Ea tempor veniam nulla commodo sint ipsum nostrud ex aute dolore qui cupidatat nostrud laborum. Mollit sint fugiat et nulla aliqua consectetur qui id cillum nostrud dolore do culpa.",
    },
    {
        name: "Atkins Wolfe",
        rating: 19,
        clients: 8,
        dairys: 5,
        nagruzka: 9,
        tags: ["occaecat", "est", "ut", "est"],
        commet:
            "Lorem duis tempor ea reprehenderit culpa mollit id voluptate. Sint id ut eu ad quis dolore eu sit tempor veniam cillum. Irure consequat anim reprehenderit Lorem amet veniam laboris anim elit. Officia non quis nisi culpa sunt ipsum sunt Lorem excepteur irure fugiat cupidatat consectetur elit.",
    },
    {
        name: "Gallagher Rutledge",
        rating: 44,
        clients: 10,
        dairys: 3,
        nagruzka: 8,
        tags: ["non"],
        commet:
            "Pariatur laborum ut enim in enim tempor duis voluptate eiusmod. Qui eu labore cillum elit ipsum Lorem. Aliquip id aliqua ullamco velit magna proident elit velit. Amet anim veniam veniam cupidatat in reprehenderit magna ad. Quis occaecat duis et ad enim mollit irure consequat officia esse anim fugiat anim aute.",
    },
    {
        name: "Patrice Weiss",
        rating: 66,
        clients: 10,
        dairys: 3,
        nagruzka: 6,
        tags: ["eu", "pariatur", "officia", "culpa", "velit"],
        commet:
            "Non consectetur est pariatur ex est ut non culpa ipsum nisi ex mollit ullamco. Ea deserunt est voluptate aute adipisicing dolor anim labore aliquip ipsum in pariatur labore velit. Enim consectetur dolore velit incididunt nisi elit elit enim eu cillum magna ipsum. Pariatur exercitation esse adipisicing dolor duis nisi aliquip anim. Ea laborum aliqua duis velit minim in commodo sunt nostrud in exercitation duis esse adipisicing.",
    },
    {
        name: "Burgess Meyer",
        rating: 37,
        clients: 2,
        dairys: 10,
        nagruzka: 4,
        tags: ["fugiat", "aliquip", "duis", "ea", "ullamco"],
        commet:
            "Duis est ipsum amet sunt laborum Lorem esse ea elit. Mollit enim esse irure magna sunt nostrud amet eiusmod veniam non adipisicing est ipsum culpa. Cupidatat ipsum ipsum ea veniam incididunt id consequat aliquip anim do pariatur irure.",
    },
    {
        name: "Jennings Leach",
        rating: 85,
        clients: 4,
        dairys: 10,
        nagruzka: 6,
        tags: ["Lorem", "cillum", "sint", "ea", "nulla"],
        commet:
            "Commodo culpa officia pariatur reprehenderit do ullamco. Irure aute et aute officia labore. Fugiat esse consectetur magna velit amet consequat esse labore laboris commodo occaecat. Nisi amet mollit aliquip officia. Eu ullamco proident aliqua mollit quis sunt reprehenderit exercitation. Ad ipsum excepteur Lorem commodo et aliquip do aute excepteur reprehenderit pariatur.",
    },
    {
        name: "Mcintosh Weber",
        rating: 48,
        clients: 2,
        dairys: 7,
        nagruzka: 1,
        tags: ["consectetur", "et", "incididunt", "adipisicing", "irure"],
        commet:
            "Exercitation velit proident exercitation ex tempor minim. Nostrud ea eu tempor id veniam eu non minim nulla sit. Excepteur Lorem ipsum laborum aliquip excepteur veniam magna ex do elit pariatur aliqua nulla. Aliquip proident non dolor nulla commodo.",
    },
    {
        name: "Cecelia Fletcher",
        rating: 58,
        clients: 7,
        dairys: 10,
        nagruzka: 7,
        tags: ["nisi", "officia", "incididunt", "anim", "enim"],
        commet:
            "Velit pariatur irure eiusmod aliqua. Quis minim velit qui aliquip dolore pariatur. Lorem adipisicing esse qui in reprehenderit aliqua. Excepteur deserunt laboris id enim incididunt labore. Lorem eu aliquip id sint quis voluptate voluptate velit velit enim commodo ea. Incididunt officia consequat anim occaecat est labore deserunt id. Irure Lorem eiusmod sint consequat eu eu tempor nisi id pariatur.",
    },
    {
        name: "Espinoza Reeves",
        rating: 1,
        clients: 1,
        dairys: 4,
        nagruzka: 6,
        tags: ["aliqua"],
        commet:
            "Amet adipisicing eiusmod laborum velit aliquip incididunt culpa in dolore cupidatat officia laboris eiusmod nostrud. Do nulla fugiat dolor minim quis amet ex Lorem et irure quis duis Lorem laborum. Fugiat amet sit fugiat deserunt.",
    },
    {
        name: "Tameka Rivers",
        rating: 87,
        clients: 8,
        dairys: 3,
        nagruzka: 2,
        tags: ["irure", "ex", "dolor", "officia"],
        commet:
            "Consectetur commodo in laboris incididunt. Mollit amet ullamco cupidatat fugiat aliquip irure proident. Ex in duis nostrud exercitation ullamco sunt aliquip elit minim fugiat culpa. Aute cillum ea est id exercitation eu fugiat. Dolor commodo irure id amet sit. Elit do velit sit ut id sint occaecat id commodo do.",
    },
    {
        name: "Tyson Chase",
        rating: 39,
        clients: 9,
        dairys: 4,
        nagruzka: 6,
        tags: ["irure", "velit", "eiusmod", "aliquip"],
        commet:
            "Do velit exercitation tempor commodo mollit culpa elit duis. Occaecat laboris ipsum ex esse dolore nostrud dolor. Commodo velit consequat duis sit esse consectetur pariatur aute proident consectetur ex do. Reprehenderit irure nisi Lorem ad anim labore dolor aute adipisicing est. Dolor mollit minim nisi proident fugiat esse ex aliquip. Id sint officia consectetur cupidatat fugiat.",
    },
    {
        name: "Jeannette Armstrong",
        rating: 77,
        clients: 2,
        dairys: 7,
        nagruzka: 1,
        tags: ["id", "in"],
        commet:
            "Anim qui quis deserunt in veniam anim quis est cupidatat sunt sint. Occaecat ea eiusmod anim excepteur officia proident id ad Lorem elit. Sunt sit minim deserunt nulla ex excepteur voluptate labore eiusmod labore consectetur. Occaecat mollit sint laboris quis minim ex ipsum occaecat aute dolore dolore officia. Consectetur eiusmod exercitation eiusmod veniam est reprehenderit dolore esse veniam nostrud non Lorem voluptate.",
    },
    {
        name: "Haley Hutchinson",
        rating: 44,
        clients: 1,
        dairys: 5,
        nagruzka: 2,
        tags: ["velit", "voluptate", "do", "pariatur"],
        commet:
            "Cupidatat officia aliquip reprehenderit velit velit. Qui dolor exercitation eu aute amet velit irure do id dolor adipisicing voluptate. Eiusmod et nostrud pariatur dolor anim. Et id ullamco occaecat voluptate consequat ea ullamco eiusmod.",
    },
    {
        name: "Fitzpatrick Summers",
        rating: 78,
        clients: 7,
        dairys: 1,
        nagruzka: 3,
        tags: ["enim", "ullamco", "adipisicing"],
        commet:
            "Et adipisicing nisi aute sint aliqua eu laboris nulla ad. Commodo Lorem esse labore mollit. Aliquip eiusmod ea officia minim sunt. Nulla nostrud ea culpa ullamco aliqua velit aute ut. Voluptate incididunt pariatur est culpa elit magna ullamco.",
    },
];

const dairyJson = [
    {
        id: 0,
        date: "21.10.2014",
        deadline: "22.09.2017",
        user: "@Keisha",
        remained: "20ч. 09мин.",
        chars: 865,
        status: "На проверке",
        specialist: "Corine Beard",
        actions: "Прикрепить",
    },
    {
        id: 1,
        date: "20.06.2019",
        deadline: "30.10.2020",
        user: "@Benita",
        remained: "05ч. 34мин.",
        chars: 518,
        status: "На проверке",
        specialist: "Irwin Key",
        actions: "К дневнику",
    },
    {
        id: 2,
        date: "02.03.2015",
        deadline: "04.04.2018",
        user: "@Katelyn",
        remained: "14ч. 41мин.",
        chars: 592,
        status: "Конфликт",
        specialist: "Perkins Moreno",
        actions: "К дневнику",
    },
    {
        id: 3,
        date: "26.04.2019",
        deadline: "11.07.2017",
        user: "@Sheree",
        remained: "02ч. 33мин.",
        chars: 669,
        status: "Прикреплен",
        specialist: "Iris Williamson",
        actions: "К дневнику",
    },
    {
        id: 4,
        date: "19.08.2019",
        deadline: "12.09.2014",
        user: "@Louisa",
        remained: "15ч. 57мин.",
        chars: 886,
        status: "На проверке",
        specialist: "Sawyer Powell",
        actions: "К дневнику",
    },
    {
        id: 5,
        date: "17.07.2014",
        deadline: "31.03.2019",
        user: "@Nell",
        remained: "12ч. 54мин.",
        chars: 593,
        status: "Прикреплен",
        specialist: "Alberta Huffman",
        actions: "Прикрепить",
    },
    {
        id: 6,
        date: "26.06.2015",
        deadline: "27.11.2017",
        user: "@Neva",
        remained: "18ч. 53мин.",
        chars: 456,
        status: "Прикреплен",
        specialist: "Gray Schwartz",
        actions: "Прикрепить",
    },
    {
        id: 7,
        date: "30.11.2020",
        deadline: "04.08.2014",
        user: "@Christina",
        remained: "06ч. 08мин.",
        chars: 343,
        status: "Конфликт",
        specialist: "Gretchen Cain",
        actions: "К дневнику",
    },
    {
        id: 8,
        date: "26.11.2018",
        deadline: "23.04.2018",
        user: "@Hodges",
        remained: "00ч. 51мин.",
        chars: 353,
        status: "Новый",
        specialist: "Huber Murphy",
        actions: "Прикрепить",
    },
    {
        id: 9,
        date: "22.06.2018",
        deadline: "22.03.2020",
        user: "@Hicks",
        remained: "18ч. 55мин.",
        chars: 732,
        status: "Конфликт",
        specialist: "Gordon Lowe",
        actions: "Прикрепить",
    },
    {
        id: 10,
        date: "12.08.2017",
        deadline: "17.11.2018",
        user: "@Dillon",
        remained: "22ч. 45мин.",
        chars: 235,
        status: "Прикреплен",
        specialist: "Norris Slater",
        actions: "Прикрепить",
    },
    {
        id: 11,
        date: "16.11.2017",
        deadline: "04.01.2016",
        user: "@Jacklyn",
        remained: "18ч. 38мин.",
        chars: 800,
        status: "Прикреплен",
        specialist: "Norma Crawford",
        actions: "К дневнику",
    },
    {
        id: 12,
        date: "14.11.2016",
        deadline: "24.03.2016",
        user: "@Carol",
        remained: "18ч. 07мин.",
        chars: 818,
        status: "На проверке",
        specialist: "Forbes Henson",
        actions: "К дневнику",
    },
    {
        id: 13,
        date: "29.03.2014",
        deadline: "30.01.2016",
        user: "@Lloyd",
        remained: "19ч. 47мин.",
        chars: 786,
        status: "Прикреплен",
        specialist: "Vazquez Landry",
        actions: "Прикрепить",
    },
    {
        id: 14,
        date: "08.09.2017",
        deadline: "11.07.2020",
        user: "@Harper",
        remained: "10ч. 33мин.",
        chars: 846,
        status: "На проверке",
        specialist: "Shaffer Hobbs",
        actions: "Прикрепить",
    },
    {
        id: 15,
        date: "25.08.2020",
        deadline: "20.10.2014",
        user: "@Anne",
        remained: "13ч. 23мин.",
        chars: 418,
        status: "На проверке",
        specialist: "Preston Cooke",
        actions: "Прикрепить",
    },
    {
        id: 16,
        date: "08.06.2015",
        deadline: "15.03.2019",
        user: "@Ida",
        remained: "02ч. 41мин.",
        chars: 400,
        status: "Конфликт",
        specialist: "Barron Marshall",
        actions: "К дневнику",
    },
    {
        id: 17,
        date: "16.01.2014",
        deadline: "17.03.2019",
        user: "@Sophie",
        remained: "02ч. 03мин.",
        chars: 333,
        status: "Новый",
        specialist: "Chandler Huff",
        actions: "Прикрепить",
    },
    {
        id: 18,
        date: "22.05.2015",
        deadline: "17.07.2019",
        user: "@Dorthy",
        remained: "05ч. 04мин.",
        chars: 536,
        status: "На проверке",
        specialist: "Pansy Diaz",
        actions: "Прикрепить",
    },
    {
        id: 19,
        date: "01.04.2017",
        deadline: "21.08.2018",
        user: "@Hayes",
        remained: "10ч. 47мин.",
        chars: 281,
        status: "Конфликт",
        specialist: "Scott Estes",
        actions: "Прикрепить",
    },
    {
        id: 20,
        date: "08.09.2019",
        deadline: "25.09.2017",
        user: "@Chris",
        remained: "04ч. 36мин.",
        chars: 477,
        status: "Прикреплен",
        specialist: "Janet Bush",
        actions: "Прикрепить",
    },
    {
        id: 21,
        date: "24.09.2016",
        deadline: "19.06.2015",
        user: "@Stacie",
        remained: "16ч. 02мин.",
        chars: 321,
        status: "На проверке",
        specialist: "Shelton Berry",
        actions: "К дневнику",
    },
    {
        id: 22,
        date: "13.05.2014",
        deadline: "08.01.2015",
        user: "@Levy",
        remained: "18ч. 24мин.",
        chars: 740,
        status: "Конфликт",
        specialist: "Miles Walton",
        actions: "Прикрепить",
    },
    {
        id: 23,
        date: "21.02.2019",
        deadline: "04.06.2015",
        user: "@Gilmore",
        remained: "04ч. 07мин.",
        chars: 495,
        status: "Новый",
        specialist: "Roach Osborne",
        actions: "К дневнику",
    },
    {
        id: 24,
        date: "18.02.2018",
        deadline: "28.02.2019",
        user: "@Luz",
        remained: "20ч. 39мин.",
        chars: 738,
        status: "Конфликт",
        specialist: "Valdez Stout",
        actions: "Прикрепить",
    },
    {
        id: 25,
        date: "13.11.2014",
        deadline: "16.07.2017",
        user: "@Bishop",
        remained: "16ч. 47мин.",
        chars: 474,
        status: "На проверке",
        specialist: "Castillo Santana",
        actions: "Прикрепить",
    },
    {
        id: 26,
        date: "03.07.2019",
        deadline: "30.11.2016",
        user: "@Kris",
        remained: "17ч. 49мин.",
        chars: 896,
        status: "На проверке",
        specialist: "Richards Mercer",
        actions: "К дневнику",
    },
    {
        id: 27,
        date: "13.12.2020",
        deadline: "08.11.2020",
        user: "@Frieda",
        remained: "21ч. 16мин.",
        chars: 526,
        status: "На проверке",
        specialist: "Erickson Cardenas",
        actions: "Прикрепить",
    },
    {
        id: 28,
        date: "20.06.2019",
        deadline: "26.01.2016",
        user: "@Leah",
        remained: "06ч. 43мин.",
        chars: 710,
        status: "На проверке",
        specialist: "Munoz Stokes",
        actions: "К дневнику",
    },
    {
        id: 29,
        date: "27.09.2020",
        deadline: "28.12.2017",
        user: "@Sherri",
        remained: "09ч. 42мин.",
        chars: 648,
        status: "Новый",
        specialist: "Nona Riley",
        actions: "Прикрепить",
    },
    {
        id: 30,
        date: "16.03.2018",
        deadline: "07.02.2015",
        user: "@Schmidt",
        remained: "21ч. 36мин.",
        chars: 455,
        status: "Конфликт",
        specialist: "Oliver Bray",
        actions: "Прикрепить",
    },
    {
        id: 31,
        date: "01.06.2020",
        deadline: "20.05.2015",
        user: "@Margarita",
        remained: "03ч. 54мин.",
        chars: 591,
        status: "Конфликт",
        specialist: "Kline Hamilton",
        actions: "К дневнику",
    },
    {
        id: 32,
        date: "25.01.2020",
        deadline: "13.07.2020",
        user: "@Workman",
        remained: "13ч. 51мин.",
        chars: 298,
        status: "Конфликт",
        specialist: "Briggs Shannon",
        actions: "К дневнику",
    },
    {
        id: 33,
        date: "23.10.2017",
        deadline: "27.12.2020",
        user: "@Garza",
        remained: "17ч. 17мин.",
        chars: 339,
        status: "На проверке",
        specialist: "Washington Wright",
        actions: "Прикрепить",
    },
    {
        id: 34,
        date: "24.01.2020",
        deadline: "14.07.2015",
        user: "@Thompson",
        remained: "19ч. 43мин.",
        chars: 768,
        status: "Новый",
        specialist: "Garrison Chen",
        actions: "Прикрепить",
    },
    {
        id: 35,
        date: "20.02.2015",
        deadline: "05.09.2018",
        user: "@Janna",
        remained: "07ч. 36мин.",
        chars: 422,
        status: "Прикреплен",
        specialist: "Rachel Barron",
        actions: "Прикрепить",
    },
    {
        id: 36,
        date: "21.05.2016",
        deadline: "10.08.2018",
        user: "@Conley",
        remained: "02ч. 43мин.",
        chars: 798,
        status: "Конфликт",
        specialist: "Melton Ochoa",
        actions: "Прикрепить",
    },
    {
        id: 37,
        date: "12.01.2017",
        deadline: "25.08.2014",
        user: "@Maryanne",
        remained: "09ч. 06мин.",
        chars: 900,
        status: "Конфликт",
        specialist: "Milagros Ryan",
        actions: "Прикрепить",
    },
    {
        id: 38,
        date: "09.10.2019",
        deadline: "17.05.2018",
        user: "@Margaret",
        remained: "19ч. 17мин.",
        chars: 257,
        status: "На проверке",
        specialist: "Antonia Blair",
        actions: "Прикрепить",
    },
    {
        id: 39,
        date: "14.09.2017",
        deadline: "18.04.2015",
        user: "@Velez",
        remained: "05ч. 08мин.",
        chars: 599,
        status: "Новый",
        specialist: "Snider Mcfarland",
        actions: "Прикрепить",
    },
    {
        id: 40,
        date: "24.02.2018",
        deadline: "17.03.2019",
        user: "@Ryan",
        remained: "04ч. 51мин.",
        chars: 761,
        status: "Прикреплен",
        specialist: "Moreno Robinson",
        actions: "К дневнику",
    },
    {
        id: 41,
        date: "08.06.2014",
        deadline: "16.02.2017",
        user: "@Bender",
        remained: "07ч. 07мин.",
        chars: 383,
        status: "Конфликт",
        specialist: "Ivy Boyd",
        actions: "Прикрепить",
    },
    {
        id: 42,
        date: "16.06.2020",
        deadline: "10.01.2021",
        user: "@Solis",
        remained: "21ч. 08мин.",
        chars: 319,
        status: "На проверке",
        specialist: "Camacho Hahn",
        actions: "К дневнику",
    },
    {
        id: 43,
        date: "01.05.2018",
        deadline: "15.05.2016",
        user: "@Hinton",
        remained: "10ч. 16мин.",
        chars: 354,
        status: "Прикреплен",
        specialist: "Bonita Ward",
        actions: "Прикрепить",
    },
    {
        id: 44,
        date: "04.07.2019",
        deadline: "30.10.2019",
        user: "@Jerri",
        remained: "21ч. 25мин.",
        chars: 570,
        status: "Конфликт",
        specialist: "Bolton Sellers",
        actions: "Прикрепить",
    },
    {
        id: 45,
        date: "09.05.2017",
        deadline: "14.01.2017",
        user: "@Hudson",
        remained: "12ч. 36мин.",
        chars: 543,
        status: "На проверке",
        specialist: "Maritza Hays",
        actions: "К дневнику",
    },
    {
        id: 46,
        date: "01.07.2018",
        deadline: "19.01.2015",
        user: "@Dunlap",
        remained: "18ч. 18мин.",
        chars: 445,
        status: "На проверке",
        specialist: "Shannon Dixon",
        actions: "К дневнику",
    },
    {
        id: 47,
        date: "09.11.2018",
        deadline: "21.01.2017",
        user: "@Richmond",
        remained: "10ч. 05мин.",
        chars: 477,
        status: "Прикреплен",
        specialist: "Kathrine Hunter",
        actions: "К дневнику",
    },
    {
        id: 48,
        date: "18.03.2017",
        deadline: "18.09.2020",
        user: "@Joan",
        remained: "15ч. 53мин.",
        chars: 603,
        status: "Конфликт",
        specialist: "Holder Patrick",
        actions: "К дневнику",
    },
    {
        id: 49,
        date: "20.11.2017",
        deadline: "05.12.2014",
        user: "@Quinn",
        remained: "09ч. 19мин.",
        chars: 429,
        status: "Конфликт",
        specialist: "Yang Bryant",
        actions: "Прикрепить",
    },
    {
        id: 50,
        date: "21.07.2019",
        deadline: "24.09.2014",
        user: "@Vaughan",
        remained: "15ч. 25мин.",
        chars: 763,
        status: "На проверке",
        specialist: "House Woodward",
        actions: "Прикрепить",
    },
    {
        id: 51,
        date: "18.09.2019",
        deadline: "19.03.2016",
        user: "@Terri",
        remained: "02ч. 36мин.",
        chars: 680,
        status: "Конфликт",
        specialist: "Marian Parks",
        actions: "К дневнику",
    },
    {
        id: 52,
        date: "22.03.2017",
        deadline: "30.11.2015",
        user: "@Hancock",
        remained: "19ч. 06мин.",
        chars: 456,
        status: "На проверке",
        specialist: "Belinda Bird",
        actions: "К дневнику",
    },
    {
        id: 53,
        date: "14.05.2020",
        deadline: "14.10.2020",
        user: "@Vega",
        remained: "02ч. 43мин.",
        chars: 849,
        status: "На проверке",
        specialist: "Acosta Golden",
        actions: "Прикрепить",
    },
    {
        id: 54,
        date: "15.02.2015",
        deadline: "10.11.2014",
        user: "@Gaines",
        remained: "13ч. 47мин.",
        chars: 657,
        status: "На проверке",
        specialist: "Sharlene Michael",
        actions: "Прикрепить",
    },
    {
        id: 55,
        date: "14.12.2018",
        deadline: "23.12.2019",
        user: "@Elisabeth",
        remained: "23ч. 51мин.",
        chars: 757,
        status: "Конфликт",
        specialist: "Stanton Ferguson",
        actions: "Прикрепить",
    },
    {
        id: 56,
        date: "30.11.2014",
        deadline: "06.11.2017",
        user: "@Ford",
        remained: "21ч. 17мин.",
        chars: 603,
        status: "На проверке",
        specialist: "Winnie Cox",
        actions: "К дневнику",
    },
    {
        id: 57,
        date: "08.04.2020",
        deadline: "19.09.2019",
        user: "@Wilder",
        remained: "09ч. 06мин.",
        chars: 620,
        status: "Прикреплен",
        specialist: "Wolfe Norman",
        actions: "Прикрепить",
    },
    {
        id: 58,
        date: "18.08.2019",
        deadline: "10.11.2020",
        user: "@Klein",
        remained: "08ч. 17мин.",
        chars: 314,
        status: "Конфликт",
        specialist: "Flynn Myers",
        actions: "К дневнику",
    },
    {
        id: 59,
        date: "10.03.2015",
        deadline: "24.11.2015",
        user: "@Mercer",
        remained: "22ч. 30мин.",
        chars: 893,
        status: "Новый",
        specialist: "Puckett Wooten",
        actions: "Прикрепить",
    },
    {
        id: 60,
        date: "25.08.2020",
        deadline: "12.12.2016",
        user: "@Lina",
        remained: "01ч. 59мин.",
        chars: 419,
        status: "На проверке",
        specialist: "Walsh Gill",
        actions: "Прикрепить",
    },
    {
        id: 61,
        date: "09.08.2019",
        deadline: "26.10.2017",
        user: "@Lucinda",
        remained: "11ч. 23мин.",
        chars: 848,
        status: "Конфликт",
        specialist: "Mari Roth",
        actions: "Прикрепить",
    },
    {
        id: 62,
        date: "06.04.2017",
        deadline: "10.05.2020",
        user: "@Ingrid",
        remained: "01ч. 14мин.",
        chars: 583,
        status: "Прикреплен",
        specialist: "Colette Serrano",
        actions: "Прикрепить",
    },
    {
        id: 63,
        date: "17.07.2017",
        deadline: "24.05.2016",
        user: "@Dana",
        remained: "11ч. 10мин.",
        chars: 535,
        status: "Новый",
        specialist: "Roxie Baldwin",
        actions: "Прикрепить",
    },
    {
        id: 64,
        date: "30.06.2014",
        deadline: "26.04.2018",
        user: "@Cassandra",
        remained: "08ч. 48мин.",
        chars: 450,
        status: "На проверке",
        specialist: "Waters Espinoza",
        actions: "К дневнику",
    },
    {
        id: 65,
        date: "12.11.2020",
        deadline: "13.10.2016",
        user: "@Tamera",
        remained: "17ч. 40мин.",
        chars: 835,
        status: "Прикреплен",
        specialist: "Jocelyn Moore",
        actions: "К дневнику",
    },
    {
        id: 66,
        date: "07.02.2015",
        deadline: "22.03.2017",
        user: "@Carlene",
        remained: "11ч. 37мин.",
        chars: 478,
        status: "Новый",
        specialist: "Jeannie Banks",
        actions: "Прикрепить",
    },
    {
        id: 67,
        date: "15.04.2014",
        deadline: "10.11.2020",
        user: "@Oconnor",
        remained: "05ч. 25мин.",
        chars: 836,
        status: "Прикреплен",
        specialist: "Galloway Moss",
        actions: "Прикрепить",
    },
    {
        id: 68,
        date: "21.10.2020",
        deadline: "17.03.2017",
        user: "@Graham",
        remained: "23ч. 29мин.",
        chars: 702,
        status: "Новый",
        specialist: "Susie Walls",
        actions: "К дневнику",
    },
    {
        id: 69,
        date: "11.08.2020",
        deadline: "29.01.2018",
        user: "@Weber",
        remained: "05ч. 11мин.",
        chars: 683,
        status: "Новый",
        specialist: "Battle Dillard",
        actions: "Прикрепить",
    },
    {
        id: 70,
        date: "11.04.2015",
        deadline: "29.12.2020",
        user: "@Alston",
        remained: "10ч. 59мин.",
        chars: 414,
        status: "На проверке",
        specialist: "Ochoa Watson",
        actions: "Прикрепить",
    },
    {
        id: 71,
        date: "14.06.2018",
        deadline: "02.09.2017",
        user: "@Leonor",
        remained: "18ч. 12мин.",
        chars: 809,
        status: "Конфликт",
        specialist: "Marissa Gordon",
        actions: "К дневнику",
    },
    {
        id: 72,
        date: "19.02.2017",
        deadline: "23.07.2016",
        user: "@Esther",
        remained: "09ч. 09мин.",
        chars: 494,
        status: "На проверке",
        specialist: "Chambers Perez",
        actions: "К дневнику",
    },
    {
        id: 73,
        date: "19.02.2017",
        deadline: "15.06.2018",
        user: "@Francis",
        remained: "07ч. 28мин.",
        chars: 579,
        status: "На проверке",
        specialist: "Corrine Kelly",
        actions: "Прикрепить",
    },
    {
        id: 74,
        date: "05.02.2014",
        deadline: "17.06.2017",
        user: "@Faye",
        remained: "04ч. 57мин.",
        chars: 296,
        status: "Конфликт",
        specialist: "Andrews Whitehead",
        actions: "К дневнику",
    },
    {
        id: 75,
        date: "25.09.2015",
        deadline: "30.09.2018",
        user: "@Mattie",
        remained: "06ч. 46мин.",
        chars: 690,
        status: "На проверке",
        specialist: "Shaw Maxwell",
        actions: "Прикрепить",
    },
    {
        id: 76,
        date: "05.12.2020",
        deadline: "27.10.2016",
        user: "@Holloway",
        remained: "01ч. 06мин.",
        chars: 883,
        status: "Новый",
        specialist: "Daphne Campos",
        actions: "Прикрепить",
    },
    {
        id: 77,
        date: "03.01.2016",
        deadline: "01.03.2019",
        user: "@Sutton",
        remained: "23ч. 03мин.",
        chars: 246,
        status: "Конфликт",
        specialist: "Angeline Dickson",
        actions: "К дневнику",
    },
];
